language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
install:
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: xZYMkbKN8iURWSH5E9eS6TcSDI79C2vfMSdrqBjGIKHOpXC4dCOIfJOt/YgbtxYfL2fmQybcR1g95GZfIUgFN9CwDNijkBW4rke+WKA/r8rfghf0+yg9Hh0cGgeH9espp7UBklxs3W0leLp39HOV0Vqriu/+2kRpBy71i7p5VkuDXi7u7QDrn0V5aCaDCNNovmTMwG6AL4kquyjKc5qHRzosIqih80XTiYAy5VtJDEtCQ5KhqGz3scIpD848hOXlBra5kY+NCzwWEsHxTx+EAYsn3wFQ+CuThUv6fVagSJG3K+FpDg77AI2uBEuDZcx0Ym4fXsJWJWvxHus/C/ubijcweROLRg78yRnSwbpDrY8h+ktENJ+fxjQ+0RGBFiUgKBOxcXYLxIO3ErmLFnJkR1dBHqULutQy00ubuKztfHiN4guBL1/LcEGPPiCI0BDlTlpu+YZ3dFMipd0wshdrLIkyuk+RI7+PufcSVagqUu447BQvUIY8zQd8xONXN/mpZTkWPZPzu7s5C2nHzWS0Q1Dzz1vSdC6lbLC7S1QoIhflEEjKoKJqAGmb2hPifl4DhaY4o7Xw7cVw4SJOgU5h0sjmRsQfkxPXUxc2jvZtsWr1CtIkChPWV5V4AuI2mfQcLuL8SOf5KtKgDPsHhcZMzjWUC7q0npGRQ1Ses90bdpA=
  on:
    tags: true
  skip_existing: true
